# Build stage
FROM node:20-alpine AS builder
WORKDIR /app
COPY ./package.json ./package-lock.json ./
RUN npm clean-install
COPY . .
RUN npm run build

# Deployment stage
FROM nginx:alpine-slim
EXPOSE 5173
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html