version: "3.8"

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: scoutr_database
      POSTGRES_USER: scoutr_user
      POSTGRES_PASSWORD: scoutr_password
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ${HOME}/database/scoutr:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scoutr_user -d scoutr_database"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      database:
        condition: service_healthy

  frontend:
    stdin_open: true
    build:
      dockerfile: Dockerfile.production
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      database:
        condition: service_healthy
