networks:
  scoutr_network:
    driver: bridge

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: scoutr_database
      POSTGRES_USER: scoutr_user
      POSTGRES_PASSWORD: scoutr_password
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ${HOME}/database/scoutr:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - scoutr_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scoutr_user -d scoutr_database"]
      interval: 1s
      timeout: 5s
      retries: 3

  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - scoutr_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    command: ["npm", "run", "dev"]
    networks:
      - scoutr_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
    depends_on:
      database:
        condition: service_healthy
    networks:
      - scoutr_network
