FROM node:20-bookworm-slim
RUN npx -y playwright@1.43.0 install firefox --with-deps
WORKDIR /app
COPY ./package.json ./package-lock.json ./
RUN npm ci --omit=dev
COPY . .
# CMD ["npm", "run", "dev"] 
# Note: The CMD command runs on Docker Composer to handle all the project images and on the GitHub Actions for CI

# This production image uses the "--omit=dev" flag to skip installing the developer dependencies saving around 50mb to the final image